from .chat import *
from .comment import *
from .delete import *
from .edit_posts import *
from .edit_profile import *
from .feed import *
from .follow import *
from .forgot_password import *
from .login import *
from .notification import *
from .posts import *
from .profile import *
from .register import *
from .search import *
from .security import *
from .sitemap import *
