import subprocess

cmd_str = "ls -l /tmp | awk '{print $3,$9}' | grep root"
subprocess.run(cmd_str, shell=True)


files = [".gitignore",
"README.md",
"db.sqlite3",
"first.in",
"main/__init__.py",
"main/admin.py",
"main/apps.py",
"main/forms.py",
"main/models.py",
"main/parse_time.py",
"main/sendmail.py",
"main/templates/about.html",
"main/templates/ch_password.html",
"main/templates/change.html",
"main/templates/chat.html",
"main/templates/comment.html",
"main/templates/edit.html",
"main/templates/edit_post.html",
"main/templates/find.html",
"main/templates/index.html",
"main/templates/index1.html",
"main/templates/layout.html",
"main/templates/layout1.html",
"main/templates/layout2.html",
"main/templates/layout3.html",
"main/templates/login.html",
"main/templates/mylayout.html",
"main/templates/newpost.html",
"main/templates/news.html",
"main/templates/nopage.html",
"main/templates/posts.html",
"main/templates/profile.html",
"main/templates/questions.html",
"main/templates/register.html",
"main/templates/reset.html",
"main/templates/security.html",
"main/templates/sitemap.xml",
"main/templates/test.html",
"main/tests.py",
"main/urls.py",
"main/views.py",
"manage.py",
"media/posts/4ec57921-1165-498b-97f7-b15a72360c47.png",
"static/bubble.css",
"static/chat.css",
"static/chat.js",
"static/chat.png",
"static/chat_time.js",
"static/favicon.ico",
"static/follow.js",
"static/gif.gif",
"static/icon.png",
"static/index.js",
"static/jquery.js",
"static/like.js",
"static/login.css",
"static/mylayout.css",
"static/nav_bar.css",
"static/new.png",
"static/nicepage.css",
"static/nicepage.js",
"static/notify.css",
"static/notify.js",
"static/posts.css",
"static/posts.js",
"static/profile.css",
"static/profile.png",
"static/register.js",
"static/security.css",
"static/time.js",
"static/validate.js",
"static/view_likes.js",
"viral/__init__.py",
"viral/asgi.py",
"viral/settings.py",
"viral/urls.py",
"viral/wsgi.py",
]

for i in files:
    cmd_str = f"git add {i}; git commit -m 'Updated'; git push"
    subprocess.run(cmd_str, shell=True)
