# Generated by Django 4.0.6 on 2023-04-24 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otp",
            old_name="u_name",
            new_name="username",
        ),
    ]
