# Generated by Django 4.0.6 on 2023-04-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="m_comment",
            field=models.ForeignKey(
                default="Empty",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default="Empty",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.post",
            ),
        ),
    ]
