# Generated by Django 4.0.6 on 2023-04-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_m_comment_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='m_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post'),
        ),
    ]
