# Generated by Django 4.0.6 on 2023-04-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_comment_m_comment_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.comment",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.post"
            ),
        ),
    ]
